[package]
name = "color-backtrace"
version = "0.1.0"
authors = ["Joel Höner <athre0z@zyantific.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
name = "color-backtrace-test"
path = "src/bin.rs"

[dependencies]
backtrace = "0.3"
term = "0.5"