[package]
name = "color-backtrace"
version = "0.1.1"
authors = ["Joel Höner <athre0z@zyantific.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/athre0z/color-backtrace"
description = "Colorful panic backtraces"
readme = "README.md"

keywords = [
    "backtrace",
    "color",
    "colour",
    "stacktrace",
    "pretty",
]

[dependencies]
backtrace = "0.3"
term = "0.5"